# Generated by Django 4.0.1 on 2022-03-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameleader', models.CharField(max_length=200)),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('name3', models.CharField(max_length=200)),
                ('name4', models.CharField(blank=True, max_length=200, null=True)),
                ('name5', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('rollno', models.IntegerField(max_length=6)),
                ('rollno1', models.IntegerField(max_length=6)),
                ('rollno2', models.IntegerField(max_length=6)),
                ('rollno3', models.IntegerField(max_length=6)),
                ('rollno4', models.IntegerField(blank=True, max_length=6, null=True)),
                ('rollno5', models.IntegerField(blank=True, max_length=6, null=True)),
                ('gitLinkedinLink', models.CharField(max_length=200)),
                ('department', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='Geeks.department')),
            ],
        ),
    ]
