# Generated by Django 4.0.1 on 2022-03-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Geeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('rollno', models.IntegerField(max_length=6)),
                ('gitLinkedinLink', models.CharField(max_length=200)),
                ('department', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='Geeks.department')),
            ],
        ),
    ]
